#!/usr/bin/env bash

###############################################################################
# google payload 
###############################################################################

CHIP=$(sysctl -n machdep.cpu.brand_string) # sets the variable for chipset
SRC="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# defines source of McCleaner folder ^^
APPS=$SRC/apps

osascript -e 'tell application "Finder"' -e 'activate' -e 'display dialog "We need to install a few things.
Please input your password when in the terminal window
" with title "Linq84 | McCleaner" with icon note' -e 'end tell'

echo "Welcome to McCleaner - let's get to work"
sleep 2
echo "The first thing we install is dockutil from GitHub user kcrawford"
echo "https://github.com/kcrawford/dockutil"

# Many thanks kcrawford !

for f in "$APPS/dockutil.pkg" ; 
    do sudo installer -verbose -pkg "$f" -target / ;
    done 
    echo "Dock Utlitiy Installed"

    sleep 3
echo "Now, let's install the apps"
sleep 3
echo "detecting chipset"
sleep 1
echo "."
sleep 1
echo ".."
sleep 1 
echo "..."
sleep 1
echo ".."
sleep 1
echo "."
sleep 2

    if [ "$CHIP" = "Apple M1" ] ; then
    echo "Apple M1 Chipset Detected"
    sleep 2
    echo "Installing M1 Applications"
     ## BEGIN M1 INSTALL ##

    sleep 3

echo " Installing Google Stuff"
 sleep 3

echo "Installing Google Chrome"
hdiutil mount "$APPS/googlechrome.dmg" ;
sudo cp -r /Volumes/Google\ Chrome/Google\ Chrome.app /Applications/ ;
hdiutil unmount /Volumes/Google\ Chrome

echo "Installing Google Drive"
hdiutil mount "$APPS/GoogleDrive.dmg" ;
sudo installer -pkg /Volumes/Install\ Google\ Drive/GoogleDrive.pkg -target / ; 
hdiutil unmount /Volumes/Install\ Google\ Drive/ ;

echo "Google Stuff Installed"

sleep 3

for f in "$APPS/airwatch.pkg" ; 
    do sudo installer -verbose -pkg "$f" -target / ;
    done 
echo "Airwatch Installed"

sleep 3

echo "installing slack"
hdiutil mount "$APPS/slack.dmg" 
sudo cp -r /Volumes/Slack/Slack.app /Applications/
wait 5
hdiutil unmount /Volumes/Slack

echo "Slack Installed"

echo "M1 Applications Installed"

sleep 3




else

   ## BEGIN INTEL INSTALL ##

echo "Intel Chipset Detected"
echo "Installing Intel Apps"

sleep 3

echo " Installing Google Stuff"
 sleep 3

echo "Installing Google Chrome"
hdiutil mount "$APPS/googlechrome.dmg" ;
sudo cp -r /Volumes/Google\ Chrome/Google\ Chrome.app /Applications/ ;
hdiutil unmount /Volumes/Google\ Chrome

echo "Installing Google Drive"
hdiutil mount "$APPS/GoogleDrive.dmg" ;
sudo installer -pkg /Volumes/Install\ Google\ Drive/GoogleDrive.pkg -target / ; 
hdiutil unmount /Volumes/Install\ Google\ Drive/ ;

sleep 2 
echo "Google Stuff Installed"

sleep 3

echo "installing slack"
hdiutil mount "$APPS/slack.dmg"
sudo cp -r /Volumes/Slack/Slack.app /Applications/
hdiutil unmount /Volumes/Slack
echo "Slack Installed"
sleep 3
    echo "Intel Applications installed!"
fi

echo "Installs complete."
echo "."
echo ".."
echo "..."
echo ".."
echo "."

echo "Please wait while we clean up..."


dockutil --remove all --no-restart

dockutil --add /Applications/Google\ Chrome.app  --allhomes --no-restart
dockutil --add /Applications/Google\ Drive.app  --allhomes --no-restart
dockutil --add /Applications/Google\ Docs.app  --allhomes --no-restart
dockutil --add /Applications/Slack.app  --allhomes --no-restart
echo "you're squeeky clean !"

sleep 3


pcname="$(osascript -e 'Tell application "System Events" to display dialog "Please enter your a computer name or leave blank to skip" default answer "" with answer' -e 'text returned of result' 2>/dev/null)" && /
    if [ ! -z $pcname ]; then
            echo "Thanks for that. Renaming...."
        else
            echo "Your PC name has not been changed."
            # you have forgotten to exit here
        fi

        echo "$pcname" | sudo scutil --set ComputerName "$pcname" 

        echo "$pcname" | sudo scutil --set LocalHostName "$pcname"

        echo "$pcname" | sudo scutil --set HostName "$pcname"

killall cfprefsd
killall Dock


sleep 3
osascript -e 'tell application "Finder"' -e 'activate' -e 'display dialog "Ok, all done. Make sure you reboot.
Linq84 
xo" with title "Linq84 | McCleaner" with icon note' -e 'end tell'

 