#!/usr/bin/env bash

###############################################################################
# Update Files                                                                #
###############################################################################

CHIP=$(sysctl -n machdep.cpu.brand_string) # sets the variable for chipset
SRC="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# defines source of McPayload folder ^^
# defines Unicorn USB
USB=/Volumes/UNICORN/McPayload
PKG=$USB/PKG
DMG=$USB/DMG

APPS=$SRC/apps
USB_APPS=$USB/apps

#########################################
## DOWNLOAD LIST TO USB ##############
if [[ $(mount | awk '$3 == "/Volumes/UNICORN" {print $3}') != "" ]]; then

echo "Unicorn USB is mounted, updating"
sleep 2
sudo mkdir $USB/apps
echo "."
sleep 2
echo ".."
sleep 2
echo "..."
echo "updating scripts"
cp $SRC/buildscript $USB
rm $USB/\#buildscript
cp $SRC/mcupdate $USB
cp $SRC/standard-payload $USB
cp $SRC/standard-payload $USB

echo "Unicorn USB is mounted, cleaning up old PKG files"
sleep 2
echo "."
sleep 2
echo ".."
sleep 2
echo "..."
cp -a $PKG/ $USB_APPS

rm -R $PKG

#clean up DMG
echo "cleaning up old DMG files"
sleep 2
echo "."
sleep 2
echo ".."
sleep 2
echo "..."
cp -a $DMG/ $USB_APPS
rm -R $DMG

sleep 2

echo "Downloading: Dockutil to $USB_APPS"
 sudo curl -L -o "$USB_APPS/dockutil.pkg" -k https://github.com/kcrawford/dockutil/releases/download/2.0.5/dockutil-2.0.5.pkg ;

echo "Downloading: Google Drive to $USB_APPS"
 sudo curl -L -o "$USB_APPS/GoogleDrive.dmg" -k https://dl.google.com/drive-file-stream/GoogleDrive.dmg
 
 echo "Downloading: Google Chrome to $USB_APPS"
 sudo curl -L -o "$APPS/googlechrome.dmg" -k https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
 
  echo "Downloading: Slack to $USB_APPS"
 sudo curl -L -o "$USB_APPS/slack.dmg" -k https://slack.com/ssb/download-osx-universal

 echo "Downloading: Webex to $SRC"
 sudo curl -L -o "$USB_APPS/Webex.dmg" -k https://binaries.webex.com/WebexTeamsDesktop-MACOS-Gold/Webex.dmg
 sudo curl -L -o "$USB_APPS/WebexM1.dmg" -k https://binaries.webex.com/WebexDesktop-MACOS-Apple-Silicon-Gold/Webex.dmg



else 

echo "No USB we will update to $SRC" | 

sudo mkdir $SRC/apps
#########################################
## DOWNLOAD LIST TO SOURCE ##############
sleep 2

echo "Downloading: Dockutil to $SRC"
 sudo curl -L -o "$APPS/dockutil.pkg" -k https://github.com/kcrawford/dockutil/releases/download/2.0.5/dockutil-2.0.5.pkg ;

echo "Downloading: Google Drive to $SRC"
 sudo curl -L -o "$APPS/GoogleDrive.dmg" -k https://dl.google.com/drive-file-stream/GoogleDrive.dmg
 
 echo "Downloading: Google Chrome to $SRC"
 sudo curl -L -o "$APPS/googlechrome.dmg" -k https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
 
  echo "Downloading: Slack to $SRC"
 sudo curl -L -o "$APPS/slack.dmg" -k https://slack.com/ssb/download-osx-universal

 echo "Downloading: Webex to $SRC"
 sudo curl -L -o "$APPS/Webex.dmg" -k https://binaries.webex.com/WebexTeamsDesktop-MACOS-Gold/Webex.dmg
 sudo curl -L -o "$APPS/WebexM1.dmg" -k https://binaries.webex.com/WebexDesktop-MACOS-Apple-Silicon-Gold/Webex.dmg

fi