#!/usr/bin/env bash

###############################################################################
# Update Files                                                                #
###############################################################################

CHIP=$(sysctl -n machdep.cpu.brand_string) # sets the variable for chipset
SRC="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
# defines source of McCleaner folder ^^
# defines McCleaner USB , if you name a blank USB it will write to it
USB=/Volumes/McCleaner
PKG=$USB/PKG
DMG=$USB/DMG

APPS=$SRC/apps
USB_APPS=$USB/apps

#########################################
## DOWNLOAD LIST TO USB ##############
if [[ $(mount | awk '$3 == "/Volumes/McCleaner" {print $3}') != "" ]]; then

echo "McCleaner USB is mounted, updating"
sleep 2
sudo mkdir $USB/apps
echo "."
sleep 2
echo ".."
sleep 2
echo "..."
echo "updating scripts"
cp $SRC/buildscript $USB
rm $USB/\#buildscript
cp $SRC/mcupdate $USB
cp $SRC/standard-payload $USB
cp $SRC/standard-payload $USB

echo "McCleaner USB is mounted, cleaning up old PKG files"
sleep 2
echo "."
sleep 2
echo ".."
sleep 2
echo "..."
cp -a $PKG/ $USB_APPS

rm -R $PKG

#clean up DMG
echo "cleaning up old DMG files"
sleep 2
echo "."
sleep 2
echo ".."
sleep 2
echo "..."
cp -a $DMG/ $USB_APPS
rm -R $DMG

sleep 2

echo "Downloading: Dockutil to $USB_APPS"
 sudo curl -L -o "$USB_APPS/dockutil.pkg" -k https://github.com/kcrawford/dockutil/releases/download/2.0.5/dockutil-2.0.5.pkg ;
echo "Thanks to @kcrawford for the awesome little tool here"
 
 sleep 1
echo "Downloading: Google Drive to $USB_APPS"
 sudo curl -L -o "$USB_APPS/GoogleDrive.dmg" -k https://dl.google.com/drive-file-stream/GoogleDrive.dmg
 
 echo "Downloading: Google Chrome to $USB_APPS"
 sudo curl -L -o "$APPS/googlechrome.dmg" -k https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
 
  echo "Downloading: Slack to $USB_APPS"
 sudo curl -L -o "$USB_APPS/slack.dmg" -k https://slack.com/ssb/download-osx-universal

 echo "Downloading: Github to $SRC"
 if [ "$CHIP" = "Apple M1" ] ; then
#Apple M1 source below here
 sudo curl -L -o "$USB_APPS/VScode.zip" -k https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64
 #Intel source below here
 else
 sudo curl -L -o "$USB_APPS/VScode.dmg" -k https://central.github.com/deployments/desktop/desktop/latest/darwin
fi


else 

echo "No USB we will update to $SRC" | 

sudo mkdir $SRC/apps
#########################################
## DOWNLOAD LIST TO SOURCE ##############
sleep 2

echo "Downloading: Dockutil to $SRC"
 sudo curl -L -o "$APPS/dockutil.pkg" -k https://github.com/kcrawford/dockutil/releases/download/2.0.5/dockutil-2.0.5.pkg ;

echo "Downloading: Google Drive to $SRC"
 sudo curl -L -o "$APPS/GoogleDrive.dmg" -k https://dl.google.com/drive-file-stream/GoogleDrive.dmg
 
 echo "Downloading: Google Chrome to $SRC"
 sudo curl -L -o "$APPS/googlechrome.dmg" -k https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
 
  echo "Downloading: Slack to $SRC"
 sudo curl -L -o "$APPS/slack.dmg" -k https://slack.com/ssb/download-osx-universal

  echo "Downloading: Github to $SRC"
 if [ "$CHIP" = "Apple M1" ] ; then
#Apple M1 source below here
 sudo curl -L -o "$USB_APPS/VScode.zip" -k https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64
 #Intel source below here
 else
 sudo curl -L -o "$USB_APPS/VScode.dmg" -k https://central.github.com/deployments/desktop/desktop/latest/darwin
fi
fi